// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using SampleNotify.Models.Entity;

namespace SampleNotify.Models
{
    public partial class DataNotifyDbContext : DbContext
    {
        public DataNotifyDbContext()
        {
        }

        public DataNotifyDbContext(DbContextOptions<DataNotifyDbContext> options)
            : base(options)
        {
        }
        
        

        public virtual DbSet<CustomerNotifyConfig> CustomerNotifyConfig { get; set; }
        public virtual DbSet<Emailtemplate> Emailtemplate { get; set; }
        public virtual DbSet<Notify> Notify { get; set; }
        public virtual DbSet<NotifyConfig> NotifyConfig { get; set; }
        public virtual DbSet<NotifyConfigGroup> NotifyConfigGroup { get; set; }
        public virtual DbSet<SubscribeNotify> SubscribeNotify { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            //modelBuilder.ApplyConfiguration(new CustomerNotifyConfigConfiguration());
            //modelBuilder.ApplyConfiguration(new EmailtemplateConfiguration());
            //modelBuilder.ApplyConfiguration(new NotifyConfiguration());
            //modelBuilder.ApplyConfiguration(new NotifyConfigConfiguration());
            //modelBuilder.ApplyConfiguration(new NotifyConfigGroupConfiguration());
            //modelBuilder.ApplyConfiguration(new SubscribeNotifyConfiguration());
            modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
