// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace SampleNotify.Models
{
    public class CustomerNotifyConfigConfiguration : IEntityTypeConfiguration<CustomerNotifyConfig>
    {
        public void Configure(EntityTypeBuilder<CustomerNotifyConfig> entity)
        {
            entity.ToTable("CUSTOMER_NOTIFY_CONFIG");

            entity.Property(e => e.AccountId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("CustomerId");

            entity.Property(e => e.AppId)
                .IsRequired()
                .HasMaxLength(450)
                .HasComment("Mã App (VD: ichiba-portal-web)");

            entity.Property(e => e.NotifyConfigCode)
                .IsRequired()
                .HasMaxLength(255);
        }
    }
}
