// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using SampleNotify.Models.Entity;

namespace SampleNotify.Models
{
    public class NotifyConfigGroupConfiguration : IEntityTypeConfiguration<NotifyConfigGroup>
    {
        public void Configure(EntityTypeBuilder<NotifyConfigGroup> entity)
        {
            entity.ToTable("NOTIFY_CONFIG_GROUP");

            entity.Property(e => e.AppId)
                .IsRequired()
                .HasMaxLength(255);

            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255);
        }
    }
}
