// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace SampleNotify.Models
{
    public class SubscribeNotifyConfiguration : IEntityTypeConfiguration<SubscribeNotify>
    {
        public void Configure(EntityTypeBuilder<SubscribeNotify> entity)
        {
            entity.ToTable("SUBSCRIBE_NOTIFY");

            entity.Property(e => e.AppId)
                .IsRequired()
                .HasColumnName("app_id")
                .HasMaxLength(255);

            entity.Property(e => e.Browser)
                .HasColumnName("browser")
                .HasMaxLength(255);

            entity.Property(e => e.CreatedOnUtc)
                .HasColumnName("created_on_utc")
                .HasColumnType("datetime");

            entity.Property(e => e.Device)
                .HasColumnName("device")
                .HasMaxLength(255);

            entity.Property(e => e.DeviceId)
                .HasColumnName("device_id")
                .HasMaxLength(255);

            entity.Property(e => e.DeviceType)
                .HasColumnName("device_type")
                .HasMaxLength(255);

            entity.Property(e => e.FcmToken)
                .IsRequired()
                .HasColumnName("fcm_token")
                .HasMaxLength(1000);

            entity.Property(e => e.LastActivityDateUtc)
                .HasColumnName("last_activity_date_utc")
                .HasColumnType("datetime");

            entity.Property(e => e.LoggedOut).HasColumnName("logged_out");

            entity.Property(e => e.Os)
                .HasColumnName("os")
                .HasMaxLength(255);

            entity.Property(e => e.OsVersion)
                .HasColumnName("os_version")
                .HasMaxLength(255);

            entity.Property(e => e.Topic)
                .HasColumnName("topic")
                .HasMaxLength(255);

            entity.Property(e => e.UserId)
                .HasColumnName("user_id")
                .HasMaxLength(255);

            entity.Property(e => e.UserName)
                .HasColumnName("user_name")
                .HasMaxLength(255);
        }
    }
}
