// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using SampleNotify.Models.Entity;

namespace SampleNotify.Models
{
    public partial class NotifyConfig
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        /// <summary>
        /// Nhóm cấu hình (Enum: NotifyConfigGroup)
        /// </summary>
        public int GroupId { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public bool Required { get; set; }

        public virtual NotifyConfigGroup Group { get; set; }
    }
}