// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SampleNotify.Models
{
    public partial class SubscribeNotify
    {
        public int Id { get; set; }
        public string FcmToken { get; set; }
        public string AppId { get; set; }
        public string Browser { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string Device { get; set; }
        public string DeviceId { get; set; }
        public string DeviceType { get; set; }
        public DateTime? LastActivityDateUtc { get; set; }
        public bool LoggedOut { get; set; }
        public string Os { get; set; }
        public string OsVersion { get; set; }
        public string Topic { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
    }
}